sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  aliyun:
    oss:
      endpoint: https://oss-cn-beijing.aliyuncs.com
      bucketName: java-070102
      region: cn-beijing
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    app-id: wx2920591d328ccee8
    secret: 22ff59bf87b19932769d46b1850111e5